### ISSUE TITLE
Signbytes

### ISSUE THREAD

**Issue by joseandradez** [terra-money/station-mobile#10]
I was trying to use sign bytes from the wallet provider via wallet connect but it says it's not supported. Any chance it will be added soon?

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by trust0212** [comment]
I got the same issue before.
@joseandradez You need to install latest terra station app.
It works now.

**Comment by alecande11** [comment]
Wallet connect has been updated and should work now.
