### ISSUE TITLE
TerraTWD stablecoin is not listed and crashes the app if clicked on

### ISSUE THREAD

**Issue by LiquidSpirit** [terra-money/station-mobile#14]
TerraTWD stablecoin token (TWT) is not properly listed, and if it exists in your wallet and you click on it, it will crash the app. Swap page also lists it as a TWD token and cannot be swapped for anything
![Screenshot_20220209-222657_Station](https://user-images.githubusercontent.com/19887604/153221800-d0028b89-e09d-4044-917c-2b3c28c3bd4b.jpg)
![Screenshot_20220209-222717_Station](https://user-images.githubusercontent.com/19887604/153221816-6a34b9c8-ebea-4a1b-b2a2-1075a97665c0.jpg)
.

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by hanwong** [comment]
This isuue is fixed.  'utwd' terra native was changed incorrectly. so i revised it.
