### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by jwebcat** [terra-money/station-mobile#23]
Greetings,

First to all the devs:
Thanks for all your work on this, it's really solid 🙏 .

I would really like for there to be a dark mode in the app that matches the desktop app for Mac. Is there a want for that? 
Not sure if this is the right forum for this.

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)
