### ISSUE TITLE
please publish version 1.5.4 on github

### ISSUE THREAD

**Issue by makinghappen** [terra-money/station-mobile#26]
Hi,
I have 1.5.3 version installed from the github releases, but now cannot use it because it wants to be updated, and I cannot update it to google play version because of a different signature. Please release the 1.5.4 on Github!

**Comment by hanwong** [comment]
The file is not an official version. Please back up your information, delete the app installed now, and install the official version of Google Play.

**Comment by makinghappen** [comment]
I am not using Play store, and have been using version from github for a long time. Can you please publish the latest release here?
