### ISSUE TITLE
1.5.4 and 1.5.3 published on releases page have different signatures

### ISSUE THREAD

**Issue by makinghappen** [terra-money/station-mobile#28]
@hanwong thank you for publishing 1.5.4, but the signature is different from 1.5.3 published by @b0okuhe, can you please rebuild it using the same signature?

**Comment by hanwong** [comment]
Sorry, It was builded with same key, can you reinstall after removing previous version?

**Comment by makinghappen** [comment]
@hanwong please check, the signatures are different...
