### ISSUE TITLE
Android mobile wallet not working on android AOSP without Google services

### ISSUE THREAD

**Issue by samvaol** [terra-money/station-mobile#32]
App not working on android custom rom (not rooted, Lineage OS 18.1). App says that "The device is rooted. For security reasons cannot be run on a rooted device."
![Screenshot_20220406-080140_Station](https://user-images.githubusercontent.com/70532389/161899285-33eabe27-cbb1-464a-bdc0-27e745677d03.png)

**Comment by hanwong** [comment]
Did you install Lineage OS yourself?

**Comment by Brown1124567** [comment]
Hi @samvaol This is a mainnet related issue, for swift solution. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [TERRA DEVELOPERS LIVE CHAT ](https://agora.terras.live/) To help you sort this out right away

**Comment by kj** [comment]
I'm also getting this message on LineageOS 18.1 on my OnePlus 8 **with** Google Play Services, and my device is not rooted.

**Comment by hanwong** [comment]
@kj 
OnePlus8's official os is Oxygen, How did you install LineageOS?
https://www.oneplus.com/oxygenos11?from=8

**Comment by kj** [comment]
I followed the instructions here:

https://wiki.lineageos.org/devices/instantnoodle/install

AFAIU (though I'm not experienced with Android), this involves unlocking the bootloader, but not enabling root access.

**Comment by hanwong** [comment]
@kj If you don't use official os, it seems to be rooted device.

**Comment by kj** [comment]
I ran this:

https://play.google.com/store/apps/details?id=com.scottyab.rootbeer.sample

It passed every check except for 'Dangerous Props'. Seems to be related to this:

https://github.com/scottyab/rootbeer/issues/181

There is a PR here:

https://github.com/scottyab/rootbeer/pull/192

From what I've read, it sounds like LineageOS sets `ro.secure` to 1, and `ro.debuggable` (apparently enables ADB root) also to 1, so with the PR (if merged) it should pass this check, as `ro.secure` is already 1.

**Comment by hanwong** [comment]
@kj but it's not seems to be meged on master branch and latest version had been updated on "24 May 2021"

**Comment by gramx** [comment]
Station uses a plugin called RootBeer as per @kj's post, it sometimes flags things wrong as it goes by several different indicators as I understand it this is because there is no clear indicator of if a device is rooted. 

I would suggest perhaps we make the root prompt a warning and not a block of access for these edge cases. I had already updated it once to ignore BusyBox for non-rooted one-plus phones. There is a ticket requesting the root check be optional here:
https://github.com/terra-money/station-mobile/issues/9

**Comment by hanwong** [comment]
We just support official OS belongs to devices, and will not be supported custom OS because any security issues.

**Comment by Tachi107** [comment]
> will not be supported custom OS because any security issues.

Could you expand on that, please? Custom OSses are often _more_ secure that the stock OS, for multiple reasons.

There are hardened OSses like @GrapheneOS that significantly improve the security of the device, even when still supported by the OEM.

And you also have to consider that many users have phones that no longer receive updates from the manufacturer, and using a custom OS is the _only_ option that can provide a bit more security, thanks to partial security updates (only the ones that fix software bugs, as firmware patches can only come from the manufacturer)

**Comment by Uncle-Chicken** [comment]
Seems like because of this its required to buy a new phone every 2 years.
If important apps (banking / crypto) do not work on Lineage, its basically useless.
