### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by hemantasapkota** [terra-money/station-mobile#34]
Hi, I encountered several build issues in the `main` branch. Hopefully easy fixes for the team! Details below

1. Invalid `Podfile` file: unkown keywords: "Flipper", "Flipper-Folly", "Flipper-RSocket

![Screen Shot 2022-04-17 at 12 00 34 pm](https://user-images.githubusercontent.com/896157/163697079-4db50bef-64ab-4bdb-801b-6c21dc06b58f.png)

2. Merge conflicts on `src/hooks/userConfim.ts`

![Screen Shot 2022-04-17 at 12 02 55 pm](https://user-images.githubusercontent.com/896157/163697109-8580379b-55f9-476b-96dc-e1c3c3c16387.png)

3. Merge conflicts on `src/screens/auth/ConnectLedger/DeviceSelector.tsx`

![Screen Shot 2022-04-17 at 12 04 06 pm](https://user-images.githubusercontent.com/896157/163697134-d37013f8-4ae2-41b2-a130-a8503fd54e66.png)

**Comment by hanwong** [comment]
Thank you for reports. 
but try reinstall npm modules and link react-native to solve 1st issue.
