### ISSUE TITLE
Documented feature URL Scheme is not working anymore?

### ISSUE THREAD

**Issue by arty-terra** [terra-money/station-mobile#43]
Hi guys. While making the new version of PaywithTerra I noticed that documented "URL Scheme" of mobile app is not working anymore.

Any plans to fix that in the near future?

https://docs.terra.money/docs/develop/wallet-provider/station-mobile.html#url-scheme

How to test:
- Navigate by prepared link in [my example](https://codepen.io/arty-terra/full/xxWrVBg)

<details>
  <summary>Screenshot</summary>
  
![telegram-cloud-photo-size-2-5393118922837966133-y](https://user-images.githubusercontent.com/89657732/180401692-6dde5d7b-dc60-4d7e-92cd-61cd4434423a.jpg)
  
</details>

**Comment by hanwong** [comment]
Current version is missing out this feature.
I fixed it on 2.0.0-v158.
Thank you for reporting.

**Comment by arty-terra** [comment]
@hanwong The issue was fixed now for QR-code scanning, but still happened when trying to navigate such link from phone browser (the Station Mobile was opened, but shows error about "transaction is not awailable at the moment")

**Comment by hanwong** [comment]
@arty-terra  Could you check again v161?  If you still get error, send me your test links..
