### ISSUE TITLE
Ledger support via USB-OTG, then ledger bluetooth support

### ISSUE THREAD

**Issue by slayorktc** [terra-money/station-mobile#5]
I tried out the Terra station mobile app on android and noticed that ledger support wasn't available. Looking at this github it wasn't clear if anyone is working on adding it. Creating this as a feature request. The terra station extension supports ledger and might be portable to the android version. Let me know if I can provide any help along the way.

**Comment by bokuhe** [comment]
We are now working on ledger support for ios and android. It's been delayed a bit due to other work, but it should be available soon.

**Comment by ZeBobo5** [comment]
Thanks. It's a important security feature we are waiting for

**Comment by wojteksbt** [comment]
Hi, any update on that? Hardware wallets are must have for security and I think whole the crypto industry does not keep up with postpc era. Not mentioning that even on PC most of protocols are not accessible without Chrome which wants to know every detail of ours life...

**Comment by javierjmc** [comment]
https://developers.ledger.com/docs/transport/react-native-bluetooth-android/

Here is some good resource for implementing bluetooth support for the ledger X on Android. If you guys need some help pushing this development forward let me know.

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by adrianso** [comment]
I am a React Native developer, and would like to see Ledger support on Terra Station too. Is there anything I can help with?

**Comment by maxxfrazer** [comment]
@adrianso at least bluetooth was added in the latest release 🎉
https://github.com/terra-money/station-mobile/releases/tag/v1.5.4
