### ISSUE TITLE
Terra station mobile connection failed.

### ISSUE THREAD

**Issue by trust0212** [terra-money/station-mobile#55]
![image](https://user-images.githubusercontent.com/83596862/203830014-8adfad23-f98c-41ad-bbd4-21b313c82990.png)
I am getting this issue when I tried on mobile phone.

Android
Anyone can help me?

**Comment by alecande11** [comment]
We need more info, and that's not the right place for this kind of question.
You can ask them on our discord: https://terra.sc/discord
