### ISSUE TITLE
iOS. Display current Undelegation

### ISSUE THREAD

**Issue by CruiseMan** [terra-money/station-mobile#6]
iOS doesn't display current `Undelegation`, but web interface does, seeking to add this functionality on mobile
<img width="1082" alt="Screen Shot 2021-10-14 at 12 51 01 PM" src="https://user-images.githubusercontent.com/15807643/137385973-f954aa5c-212f-433d-b540-d029436a3530.png">

<img width="511" alt="Screen Shot 2021-10-14 at 12 55 18 PM" src="https://user-images.githubusercontent.com/15807643/137386591-04329d6a-508a-4c19-af1a-b7dc1f4cb303.png">

> 

![IMAGE 2021-10-14 12:51:24](https://user-images.githubusercontent.com/15807643/137386012-0d12ac17-4fd9-4425-873f-2a96c1bb61ae.jpg)

**Comment by bokuhe** [comment]
We will add a ui to check the undelegation status in the next version.
